name: Clone Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install git
        run: sudo apt-get install git

      - name: Debug - Check Environment Variables
        run: |
          echo "BITBUCKET_USERNAME=${{ secrets.BITBUCKET_USERNAME }}"
          echo "BITBUCKET_APP_PASSWORD=${{ secrets.BITBUCKET_APP_PASSWORD }}"
          echo "REPO_URL=${{ secrets.REPO_URL }}"
          echo "CUSTOM_NAME=${{ secrets.CUSTOM_NAME }}"

      - name: Build Repository URL
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
          REPO_URL: ${{ secrets.REPO_URL }}
          CUSTOM_NAME: ${{ secrets.CUSTOM_NAME }}
        run: |
          FULL_URL="https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@$REPO_URL"
          echo "Full URL: $FULL_URL"
          git clone $FULL_URL $CUSTOM_NAME
          python clone_script.py
